export default function Head() {
  return (
    <>
      <title>Green Life</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/logo/greenLife_logo.png" />
    </>
  );
}