export default function Head() {
  return (
    <>
      <title>Plantilla Next.js gratuita para GreenLife y SaaS</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/brandIcons/greenLife_favicon.png" />
    </>
  );
}
